### ISSUE TITLE
Few question and 1 issue

### ISSUE THREAD

**Issue by marc2332** [pjtsearch/Git-Plus-Plus#1]
Hello @pjtsearch , it's good to see you made a plugin but I have a few things to tell you:

1- The repository and plugin name must have the name, the repository is called graviton-git-plus-plus and the plugin Git-Plus-Plus, my recommendation is to rename the repository name to Git-Plus-Plus.

2- Are you sure you wanna release the plugin into production ? I see some parts are not "finished"  like when you open the add menu, it just shows the JSON data.

3- Will you work more on it? Or just a few releases?

**Comment by pjtsearch** [comment]
Thank you @marc2332 .  Yes, I think that I probably should work on it some more before releasing it.  I'll close the PR now.
